services:
  db:
    image: postgres:16
    container_name: goit-postgres-hw12
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data_hw12:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: goit-redis-hw12
    restart: always
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: goit-api-hw12
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app

volumes:
  postgres_data_hw12:
